apiVersion: rtf.mulesoft.com/v1
kind: HTTPRouteTemplate
metadata:
  name: grpc-nginx-route
  namespace: rtf
spec:
  baseEndpoints:
    - https://*.grpc.muleaceacademy.com

  resources:
    - |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: {{ .ResourceName }}
        namespace: {{ .Namespace }}
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      spec:
        ingressClassName: nginx
        tls:
          - hosts:
              - {{ .Host }}
            secretName: grpc-muleaceacademy-tls
        rules:
          - host: {{ .Host }}
            http:
              paths:
                - path: {{ .Path }}
                  pathType: Prefix
                  backend:
                    service:
                      name: {{ .Service.Name }}
                      port:
                        name: {{ .Service.PortName }}
