apiVersion: v1
kind: Secret
metadata:
  name: grpc-wildcard-tls
  namespace: rtf
  labels:
    # Allows Runtime Fabric to synchronize the TLS secret
    # into the Mule application namespace.
    rtf.mulesoft.com/synchronized: "true"

type: kubernetes.io/tls

stringData:
  # Use the full certificate chain:
  # leaf certificate + intermediate certificates.
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_FULLCHAIN_CERTIFICATE
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_YOUR_PRIVATE_KEY
    -----END PRIVATE KEY-----
